import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: "q1",
    question: "¿Que significa cuando decimos guacala?",
    options: [
      { id: "a", text: "Cuando llamamos a una guacamalla" },
      { id: "b", text: "Cuando algo nos da asco" },
      { id: "c", text: "Cuando pedimos salsa para hallacas" },
      { id: "d", text: "Ninguna de las anteriores" },
    ],
    correctAnswers: ["b"],
    allowMultiple: false,
  },
  {
    id: "q2",
    question: "¿Cuál es la capital de Venezuela?",
    options: [
      { id: "a", text: "Caracas" },
      { id: "b", text: "Barquisimeto" },
      { id: "c", text: "Merida" },
      { id: "d", text: "Barcelona" },
    ],
    correctAnswers: ["a"],
    allowMultiple: false,
  },
  {
    id: "q3",
    question: "¿Cuál es el plato típico venezolano que se come en Navidad?",
    options: [
      { id: "a", text: "Pabellón" },
      { id: "b", text: "Hallacas" },
      { id: "c", text: "Cachapas" },
      { id: "d", text: "Arepas" },
    ],
    correctAnswers: ["b"],
    allowMultiple: false,
  },
  {
    id: "q4",
    question: "¿Cómo se llama la bebida tradicional venezolana hecha de arroz?",
    options: [
      { id: "a", text: "Papelon con limon" },
      { id: "b", text: "Orchata" },
      { id: "c", text: "Parchita" },
      { id: "d", text: "Chicha" },
    ],
    correctAnswers: ["d"],
    allowMultiple: false,
  },
  {
    id: "q5",
    question: "Cuando alguien grita 'Maduro' ¿Como se responde?",
    options: [
      { id: "a", text: "Guebon !" },
      { id: "b", text: "Preso !" },
      { id: "c", text: "Coño e' tu madre!" },
      { id: "d", text: "Marico" },
    ],
    correctAnswers: ["c"],
    allowMultiple: false,
  },
  {
    id: "q6",
    question: "¿Cual es el equipo de futbol mas popular de Venezuela?",
    options: [
      { id: "a", text: "Los leones del Caracas" },
      { id: "b", text: "Navegantes del Magallanes" },
      { id: "c", text: "La Vinotinto" },
      { id: "d", text: "Caracas futbol club" },
    ],
    correctAnswers: ["c"],
    allowMultiple: false,
  },
  {
    id: "q7",
    question: "¿Que es un 'Chinazo'?",
    options: [
      { id: "a", text: "Un golpe o pelea" },
      { id: "b", text: "Una bebida venezolana" },
      { id: "c", text: "Un baile tradicional" },
      { id: "d", text: "Una frase con doble sentido" },
    ],
    correctAnswers: ["d"],
    allowMultiple: false,
  },
  {
    id: "q8",
    question: "¿Que es un chiguire?",
    options: [
      { id: "a", text: "Un capibara" },
      { id: "b", text: "Un cerdo" },
      { id: "c", text: "Un periodico" },
      { id: "d", text: "Un barco" },
    ],
    correctAnswers: ["a"],
    allowMultiple: false,
  },
  {
    id: "q9",
    question: "¿Cuántas estrellas tiene la bandera de Venezuela?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "7" },
      { id: "c", text: "8" },
      { id: "d", text: "10" },
    ],
    correctAnswers: ["c"],
    allowMultiple: false,
  },
  {
    id: "q10",
    question: "¿Cuál es el himno nacional de Venezuela?",
    options: [
      { id: "a", text: "Gloria al bravo pueblo" },
      { id: "b", text: "La Marsellesa" },
      { id: "c", text: "El Libertador" },
      { id: "d", text: "Salve a Venezuela" },
    ],
    correctAnswers: ["a"],
    allowMultiple: false,
  },
  {
    id: "q11",
    img: "https://www.purochocolate.life/wp-content/uploads/2025/02/463418510_970533178440528_1294542821758851104_n-730x913.jpg",
    question: "¿Como se llama este producto?",
    options: [
      { id: "a", text: "Palitos" },
      { id: "b", text: "Corneto" },
      { id: "c", text: "Pirulin" },
      { id: "d", text: "Pitillos" },
    ],
    correctAnswers: ["c"],
    allowMultiple: false,
  },
  {
    id: "q12",
    img: "https://wondermarket.es/wp-content/uploads/2020/12/flips-wpndermarket.webp",
    question: "¿Como se llama este producto",
    options: [
      { id: "a", text: "Cornflakes" },
      { id: "b", text: "Flips" },
      { id: "c", text: "Leche" },
      { id: "d", text: "Avellanas" },
    ],
    correctAnswers: ["b"],
    allowMultiple: false,
  },
  {
    id: "q13",
    question: "De estas palabras, ¿cuales son venezolanas?",
    options: [
      { id: "a", text: "Carajo" },
      { id: "b", text: "Chimbo" },
      { id: "c", text: "Naguara" },
      { id: "d", text: "Todas las anteriores" },
    ],
    correctAnswers: ["d"],
    allowMultiple: false,
  },
  {
    id: "q14",
    question: "",
    options: [
      { id: "a", text: "" },
      { id: "b", text: "" },
      { id: "c", text: "" },
      { id: "d", text: "" },
    ],
    correctAnswers: [],
    allowMultiple: false,
  },
  {
    id: "q15",
    question: "¿React es una librería o un framework?",
    options: [
      { id: "a", text: "Framework" },
      { id: "b", text: "Librería" },
    ],
    correctAnswers: ["b"],
    allowMultiple: false,
  },
]